
spring:
  application:
      name: tlias-web-management
# 数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 105822
# mybatis 配置
mybatis:
  configuration:
    # 启动日志输出到stdout控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名自动映射功能
    map-underscore-to-camel-case: true